In [3]:
#getting and knowing data
import pandas as pd
import numpy as np
#step 1:import dataset
df=pd.read_csv('chipotle.tsv',sep='\t')#(Tab Separated Values) – các cột cách nhau bằng một khoảng Tab.
df.head()#head mặc định hiện 5 hàng dầu tiên và full cột

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

In [4]:
#step 2:dataset overview
df.shape

(4622, 5)

In [5]:
#muốn biết mỗi cột thuộc kiểu dữ liệu nào
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   object
 3   choice_description  3376 non-null   object
 4   item_price          4622 non-null   object
dtypes: int64(2), object(3)
memory usage: 180.7+ KB

In [6]:
#print all colums file
list(df.columns)

['order_id', 'quantity', 'item_name', 'choice_description', 'item_price']

In [26]:

#muốn import hết(k phải mỗi số)thì
df.describe(include='all')

,order_id,quantity,item_name,choice_description,item_price,total_price
count,4622.000000,4622.000000,4622,3376,4622.000000,4622.000000
unique,NaN,NaN,50,1043,NaN,NaN
top,NaN,NaN,Chicken Bowl,[Diet Coke],NaN,NaN
freq,NaN,NaN,726,134,NaN,NaN
mean,927.254868,1.075725,NaN,NaN,7.464336,8.489186
std,528.890796,0.410186,NaN,NaN,4.245557,12.632060
min,1.000000,1.000000,NaN,NaN,1.090000,1.090000
25%,477.250000,1.000000,NaN,NaN,3.390000,3.990000
50%,926.000000,1.000000,NaN,NaN,8.750000,8.750000
75%,1393.000000,1.000000,NaN,NaN,9.250000,10.980000
max,1834.000000,15.000000,NaN,NaN,44.250000,663.750000

In [8]:
#loc vs iloc:vị trí theo index
df.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

In [9]:
df.loc[df.quantity==15]#ĐIỀU KIỆN

,order_id,quantity,item_name,choice_description,item_price
3598,1443,15,Chips and Fresh Tomato Salsa,NaN,$44.25

In [10]:
#select all rows with multiple condititons
df.loc[(df.quantity ==2) & (df.item_name=='Nantucket Nectar'),['order_id','quantity','item_name']]

      order_id  quantity         item_name
601        247         2  Nantucket Nectar
2379       947         2  Nantucket Nectar

In [11]:
df.index #đếm số hàng của file

RangeIndex(start=0, stop=4622, step=1)

In [12]:
#Integer Location (Vị trí số nguyên). Nó dùng để truy xuất dữ liệu dựa trên vị trí (index) thay vì tên gọi.
df.iloc[[9]]

,order_id,quantity,item_name,choice_description,item_price
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25

In [13]:
df.iloc[3:11]

,order_id,quantity,item_name,choice_description,item_price
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,1,Side of Chips,NaN,$1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25
10,5,1,Chips and Guacamole,NaN,$4.45

In [14]:
df.iloc[3:5,0:-1]#cách để giảm bớt đi column

,order_id,quantity,item_name,choice_description
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans..."

In [15]:
#DATA MANIPULATION
df.item_price.dtype

dtype('O')

In [16]:
df['item_price'] = df['item_price'].str.replace('$', '', regex=False).astype(float)
#dùng hàm apply và lambda để chuyển str về float
#lambda là 1 hàm mini siêu nhanh trên cùng một dòng mà không cần đặt tên cho nó (hàm ẩn danh)
#lambda dùng để thực hiện 1 phép tính or biến đổi đơn giản

In [17]:
print(df['item_price'].dtype)

float64

In [18]:
df.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98

In [19]:
#cách tạo thêm 1 colums mới
df['total_price']=df['quantity']*df['item_price']

In [20]:
df.head()

,order_id,quantity,item_name,choice_description,item_price,total_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39,2.39
1,1,1,Izze,[Clementine],3.39,3.39
2,1,1,Nantucket Nectar,[Apple],3.39,3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98,33.96

In [21]:
#how much was the revenue for the period in the dataset,
#tính tổng total price(1 cột)
revenue=df['total_price'].sum()
print(revenue)

39237.02

In [22]:
#which was the most-ordered items/
#item nào nhiều nhất(max)
#hàm group by
#hàm apply dùng để Là hàm dùng để áp dụng một quy tắc (hàm số) lên từng dòng hoặc từng cột của bảng dữ liệu.
x=df.groupby('item_name')['quantity'].sum()
x.sort_values(ascending=False).head(5)#từ lớn đến bé thì dùng ascending,còn k thì để trống

item_name
Chicken Bowl           761
Chicken Burrito        591
Chips and Guacamole    506
Steak Burrito          386
Canned Soft Drink      351
Name: quantity, dtype: int64

In [23]:
#tìm unique values
df.item_name.value_counts().count()#tìm số sp khác nhau

np.int64(50)

In [24]:
df.item_name.nunique()

50